apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-efs-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-efs-pv
  csi:
    driver: efs.csi.aws.com
    volumeHandle: [type your efs id] ##fs-034958dea5403127a
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-efs-pv
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: [type your efs id] ##fs-034958dea5403127a
  directoryPerms: "700"
