apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 3
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring-app
          image: yjin9187/hairpin:latest
          envFrom:
            - configMapRef:
              name: config-db-spring
            - secretRef:
              name: secret-db
          ports:
            - containerPort: 8080
