apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 3
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-nginx-app
        image: pilsu/hairpin-react:latest 
        ports:
        - containerPort: 80
